/**
 * KKM — İKON KAYDI
 *
 * Veri katmanı ikonları isimle saklar (örn. board.icon = 'Scale').
 * Burada yalnızca kullanılan ikonlar içe aktarılır; böylece lucide-react'in
 * binlerce ikonu pakete girmez (tree-shaking korunur).
 */

import {
  Activity,
  BadgeCheck,
  Boxes,
  BrainCircuit,
  ChartLine,
  CircleCheck,
  CircleHelp,
  ClipboardList,
  CloudCog,
  Code,
  Compass,
  Cpu,
  Crown,
  Eye,
  FileText,
  FlaskConical,
  Handshake,
  Headset,
  HeartHandshake,
  Landmark,
  Megaphone,
  MessagesSquare,
  Microscope,
  Moon,
  Network,
  Palette,
  PenTool,
  Presentation,
  Radar,
  Rocket,
  Scale,
  Send,
  ShieldCheck,
  Siren,
  TestTube,
  TriangleAlert,
  User,
  Users,
  Workflow,
  Zap,
} from 'lucide-react'

const ICONS = {
  Activity,
  BadgeCheck,
  Boxes,
  BrainCircuit,
  ChartLine,
  CircleCheck,
  ClipboardList,
  CloudCog,
  Code,
  Compass,
  Cpu,
  Crown,
  Eye,
  FileText,
  FlaskConical,
  Handshake,
  Headset,
  HeartHandshake,
  Landmark,
  Megaphone,
  MessagesSquare,
  Microscope,
  Moon,
  Network,
  Palette,
  PenTool,
  Presentation,
  Radar,
  Rocket,
  Scale,
  Send,
  ShieldCheck,
  Siren,
  TestTube,
  TriangleAlert,
  User,
  Users,
  Workflow,
  Zap,
}

/** İkon bileşenini adıyla döndürür; bilinmeyen ad için soru işareti ikonu */
export const getIcon = (name) => ICONS[name] ?? CircleHelp
